title: Bhaskar Srinivasan # your name (or website title) here
logo: "profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Web developer, data architect & engineering manager. 
  <br><br>
  <a href="https://www.linkedin.com/in/forbhaskarsrinivasan/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
